### ISSUE TITLE
Blank display when loading SVCLOG file

### ISSUE THREAD

**Issue by mek363** [martijns/SvclogViewer#1]
Thanks for your work! I'm running SvclogViewer 1.0.0.66 on Windows 10. I am trying to look at a .svclog file created by IIS Express. It loads the file and does not give an error, but there is a blank display. The file is attached.

[Traces.zip](https://github.com/martijns/SvclogViewer/files/111499/Traces.zip)

**Comment by martijns** [comment]
Your file only contains TraceRecord elements. SvclogViewer only reads MessageLogTraceRecord elements from the tracefile. I''ve just added an example web.config configuration (on the readme.md on the frontpage) on how to make sure you're getting the right output (for WCF-services).

See: https://github.com/martijns/SvclogViewer

**Comment by mek363** [comment]
@martijns Thanks for the example. It solved my problem. Thanks for your code!
